config/routes.rb
Rails.application.routes.draw do
  get "bikes/" => "bikes#index"
  get "bikes/new" => "bikes#new", as: :new_bike
  
  get "bikes/:id" => "bikes#show", as: :bike
  post "bikes/" => "bikes#create"
  get "bikes/:id/edit" => "bikes#edit", as: :edit_bike
  patch "bikes/:id" => "bikes#update"
  delete "bikes/:id" => "bikes#destroy"

  resources :motorbikes

end

app/models/bike.rb
class Bike

include Mongoid::Document
  field :name, type: String
  field :brand, type: String
  field :speed, type: Float
end

app/models/motorbike.rb
class Motorbike
  include Mongoid::Document
  field :name, type: String
  field :brand, type: String
  field :speed, type: Float
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/bikes_controller.rb
class BikesController < ApplicationController
	def index
	  @bikes = Bike.all
	end


	def show 
	  
	  @bike = Bike.find(params[:id])	
	end

	def new
	   
	  @bike = Bike.new	
	end

	def create
	 
	  @bike = Bike.new(bike_params)

	  if @bike.save
	    redirect_to bikes_path
	  else
	    render "new"
	  end 	
	end

	def edit
	  
	  @bike = Bike.find(params[:id])	 
	end

	def update
	  @bike = Bike.find(params[:id])

	  if @bike.update_attributes(params.require(:bike).permit(:name, :brand, :speed))
	    redirect_to bikes_path
	  else
	  	render "edit"
	  end
	end

	def destroy
	  @bike =  Bike.find(params[:id]) 
	  @bike.destroy
	  redirect_to bikes_path	
	end

	private

	def bike_params
	  params.require(:bike).permit(:name, :brand, :speed )
	end

end

app/controllers/motorbikes_controller.rb
class MotorbikesController < ApplicationController
	def index
	  @motorbikes = Motorbike.all
	end


	def show 
	  
	  @motorbike = Motorbike.find(params[:id])	
	end

	def new
	   
	  @motorbike = Motorbike.new	
	end

	def create
	 
	  @motorbike = Motorbike.new(motorbike_params)

	  if @motorbike.save
	    redirect_to motorbikes_path
	  else
	    render "new"
	  end 	
	end

	def edit
	  
	  @motorbike = Motorbike.find(params[:id])	 
	end

	def update
	  @motorbike = Motorbike.find(params[:id])

	  if @motorbike.update_attributes(params.require(:motorbike).permit(:name, :brand, :speed))
	    redirect_to motorbikes_path
	  else
	  	render "edit"
	  end
	end

	def destroy
	  @motorbike =  Motorbike.find(params[:id]) 
	  @motorbike.destroy
	  redirect_to motorbikes_path	
	end

	private

	def motorbike_params
	  params.require(:motorbike).permit(:name, :brand, :speed )
	end








end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/motorbikes_helper.rb
module MotorbikesHelper
end

app/views/bikes/edit.html.erb
<h1>Edit this bike!</h1>  

<%= form_for @bike do |f| %>

	Name: <%= f.text_field :name %>
	Brand: <%= f.text_field :brand %>
	Speed: <%= f.text_field :speed %>
	

	<%= f.submit "Submit these changes!" %>

<% end %>

<%= link_to " Back to the list", bikes_path %>

app/views/bikes/index.html.erb
<h1>Bike Rack</h1>
<%= link_to "MotorBikes", motorbikes_path %>

<ul>
 
	<% @bikes.each do |bike| %>

		<li>
			<strong><%= bike.name %></strong> -- <%= bike.brand %> <%= link_to "More info", bike_path(bike) %>

		</li>

	<% end %>

	<%= link_to "add new bike", new_bike_path %>




</ul>

app/views/bikes/new.html.erb
<h1>Add a new bike!</h1>

<%= form_for @bike do |f| %>

	Name: <%= f.text_field :name %>
	Brand: <%= f.text_field :brand %>
	Speed: <%= f.text_field :speed %>
	

	<%= f.submit "Add Bike!" %>

<% end %>

<%= link_to " Back to the list", bikes_path %>

app/views/bikes/show.html.erb
<h1> <%= @bike.name %> </h1>

<p> This bike is a <%= @bike.brand %> from <%= @bike.name %> and has <%= @bike.speed %> speeds.</p>

<%= link_to "Edit this bike!", edit_bike_path(@bike) %>

<%= link_to "Delete this bike!", :bike, method: :delete, data: { confirm: "Are you sure you want to delete this bike?" } %>
<%= link_to "Back to the list", bikes_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Bikeshop</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/motorbikes/edit.html.erb
<h1>Edit this motorbike!</h1>  

<%= form_for @motorbike do |f| %>

	Name: <%= f.text_field :name %>
	Brand: <%= f.text_field :brand %>
	Speed: <%= f.text_field :speed %>
	

	<%= f.submit "Submit these changes!" %>

<% end %>

<%= link_to " Back to the list", motorbikes_path %>

app/views/motorbikes/index.html.erb
<h1>Motorbike Rack</h1>

<ul>
 
	<% @motorbikes.each do |motorbike| %>

		<li>
			<strong><%= motorbike.name %></strong> -- <%= motorbike.brand %> <%= link_to "More info", motorbike_path(motorbike) %>

		</li>

	<% end %>

	<%= link_to "add new motorbike", new_motorbike_path %>



</ul>

app/views/motorbikes/new.html.erb
<h1>Add a new motorbike!</h1>

<%= form_for @motorbike do |f| %>

	Name: <%= f.text_field :name %>
	Brand: <%= f.text_field :brand %>
	Speed: <%= f.text_field :speed %>
	

	<%= f.submit "Add motorbike!" %>

<% end %>

<%= link_to " Back to the list", motorbikes_path %>

app/views/motorbikes/show.html.erb
<h1> <%= @motorbike.name %> </h1>

<p> This motorbike is a <%= @motorbike.brand %> from <%= @motorbike.name %> and has <%= @motorbike.speed %> speeds.</p>

<%= link_to "Edit this motorbike!", edit_motorbike_path(@motorbike) %>

<%= link_to "Delete this motorbike!", :motorbike, method: :delete, data: { confirm: "Are you sure you want to delete this motorbike?" } %>
<%= link_to "Back to the list", motorbikes_path %>